### ISSUE TITLE
Document how to purge MAM records?

### ISSUE THREAD

**Issue by amyspark** [maranda/metronome#511]
I was having a look at the code and there are no docs on how to purge an user's MAM records (the "mam_purge" protocol). Perhaps you can add an ad-hoc command or specify the procedure somewhere?

**Comment by maranda** [comment]
The purge protocol is legacy layover for Jappix's, it was the only implementation using it as far as I know that's why it's undocumented you're the first one actually asking for it in years, it's quite simple and straight away... but now deleting entries in the middle of an archive is actually against the MAM spec as it leaves the archive in an inconsistent state so purging will just leave an empty place marker in place of the messages instead to be compliant with the spec.

The programmatic API function is documented, see: https://metronome.im/documentation/api-reference/mam

For what regards the protocol itself, you could delete the whole archive by sending:
``
<iq type='set' id='juliet1'>
  <purge xmlns='http://metronome.im/protocol/mam-purge' />
</iq>
``

By adding attributes to the purge element you can fine grain the phasing out of entries:
- **id** :: to empty all messages with the following id.
- **jid** :: to empty all messages with the following jid.
- **start** :: to empty all messages from this timestamp.
- **fin** :: to empty all messages upto this timestamp.
All attributes are optional and can be freely used in whatever combination, timestamps use DateTime profile as explained in https://xmpp.org/extensions/xep-0082.html 3.2 paragraph.

Ex. to empty all messages of dumbo@circus.mil starting from 2010-07-21 at 4 am.
``
<iq type='set' id='romeo1'>
  <purge xmlns='http://metronome.im/protocol/mam-purge' jid="dumbo@circus.mil" start="2010-07-21T04:00:00Z" />
</iq>
``

**Comment by maranda** [comment]
Example snippet ported on the website documentation.
